#!/bin/sh
case "$1" in
*.awk | *.groff | *.java | *.js | *.m4 | *.php | *.pl | *.pm | *.pod | *.sh | \
	*.ad[asb] | *.asm | *.inc | *.[ch] | *.[ch]pp | *.[ch]xx | *.cc | *.hh | \
	*.lsp | *.l | *.pas | *.p | *.xml | *.xps | *.xsl | *.axp | *.ppd | *.pov | \
	*.diff | *.patch | *.py | *.rb | *.sql | *.ebuild | *.eclass | *.clj[s] | *.edn)
	pygmentize -f 256 "$1"
	;;

.bashrc | .bash_aliases | .bash_environment | env | env_local | env_functions | bashrc | bash_profile)
	pygmentize -f 256 -l sh "$1"
	;;

*)
	if grep -q "#\!/usr/bin/env bash" "$1" 2>/dev/null; then
		pygmentize -f 256 -l sh "$1"
	else
		exit 1
	fi
	;;
esac

exit 0
