---
endpoint: "https://trovemoney.atlassian.net"
#"\nuser: george.gasson@trovemoney.co.nz\n
password-source: keyring
user: Gas
login: "george.gasson@trovemoney.co.nz"
editor: ec
project: CORE


custom-commands:
  - name: mine
    help: display issues assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() and project = $JIRA_PROJECT ORDER BY priority asc, created"
      else
          # otherwise list issues for all project
          {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"
      fi
