#!/bin/bash

# +--------+
# | System |
# +--------+

alias shutdown='sudo shutdown now'
alias restart='sudo reboot'
alias suspend='sudo pm-suspend'

alias bigf= 'find / -xdev -type f -size +500M'  # display "big" files > 500M

alias df="df -H"
alias du="du -sh"

alias make="nice make"
alias less="less --ignore-case --raw-control-chars"
alias rsync="rsync --partial --progress --human-readable --compress"

if quiet_which rg
then
    alias rg="rg --colors 'match:style:nobold' --colors 'path:style:nobold'"
fi

alias sha256="shasum -a 256"

# +-----+
# | Zsh |
# +-----+

alias d='dirs -v'
for index ({1..9}) alias "$index"="cd +${index}"; unset index # directory stack
alias zmv="noglob zmv -vW"

# +----+
# | ls |
# +----+

if quiet_which exa
then
  alias ls="exa --classify --group --git"
  alias ll="exa -l --classify --group --git"
elif [ "$MACOS" ]
then
    alias ls="ls -F"
    alias lsl='ls -l'
    alias ll='ls -lahF'
    alias lls='ls -lahFtr'
    alias la='ls -A'
    alias l='ls -CF'
else
  alias ls='ls -F --color=auto'
  alias lsl='ls -l'
  alias ll='ls -lahF'
  alias lls='ls -lahFtr'
  alias la='ls -A'
  alias l='ls -CF'
fi


# +----+
# | cp |
# +----+

#alias cp="cp -irv"
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -i'
alias la='ls -alh'

# +------+
# | grep |
# +------+

alias grep='grep --color=auto'

# +------+
# | ping |
# +------+

alias pg='ping 8.8.8.8'

# +-----+
# | bat |
# +-----+

alias batl='bat --paging=never -l log'

# +--------+
# | Golang |
# +--------+

alias gob="go build"
alias gor="go run"
alias goc="go clean -i"
alias gta="go test ./..."       # go test all
alias gia="go install ./..."    # go install all

# +-----+
# | Git |
# +-----+

alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gpo='git push origin'
alias gpt='git push --tag'
alias gtd='git tag --delete'
alias gtdr='git tag --delete origin'
alias gr='git branch -r'                                                                           # display remote branch
alias gplo='git pull origin'
alias gb='git branch '
alias gc='git commit'
alias gd='git diff'
alias gco='git checkout '
alias gl='git log'
alias gr='git remote'
alias grs='git remote show'
alias glo='git log --pretty="oneline"'
alias glol='git log --graph --oneline --decorate'
alias gclean="git branch --merged | grep  -v '\\*\\|master\\|develop' | xargs -n 1 git branch -d" # Delete local branch merged with master
alias gblog="git for-each-ref --sort=committerdate refs/heads/ --format='%(HEAD) %(color:yellow)%(refname:short)%(color:reset) - %(color:red)%(objectname:short)%(color:reset) - %(contents:subject) - %(authorname) (%(color:green)%(committerdate:relative)%(color:reset))'"                                                             # git log for each branches
alias gsub="git submodule update --remote"                                                        # pull submodules

# +------+
# | tmux |
# +------+

alias tmuxk='tmux kill-session -t'
alias tmuxa='tmux attach -t'
alias tmuxl='tmux list-sessions'

# +--------+
# | docker |
# +--------+
alias docki="docker inspect"                                                    # display the information about a container
alias docke='docker exec -t -i'                                                 # going inside a container
alias dockDE='docker rm $(docker ps -a -q) && docker rmi $(docker images -q)'   # delete every containers / images
alias dockstats='docker stats $(docker ps -q)'                                  # stats on images
alias dockls='docker ps'                                                        # list docker containers
alias dockimg='docker images'                                                   # list images installed
alias dockprune='docker system prune -a'                                        # prune everything
alias dockceu='docker-compose run --rm -u $(id -u):$(id -g)'                    # run as the host user
alias dockce='docker-compose run --rm'

# +----------------+
# | docker-compose |
# +----------------+

alias docker-compose-dev='docker-compose -f docker-compose-dev.yml' # run a different config file than the default one

# +----------+
# | Personal |
# +----------+

# Folders
alias work="$HOME/Dev"
alias doc="$HOME/Documents"
alias dow="$HOME/Downloads"
alias dot="$XDG_CONFIG_HOME/dotfiles"

# +---------+
# | netstat |
# +---------+

alias port="netstat -tulpn | grep"
