# -*- mode: sh; -*-
# From the bash manual:
# When Bash is invoked as an interactive login shell, or as a non-interactive
# shell with the --login option, it first reads and executes commands from the
# file /etc/profile, if that file exists. After reading that file, it looks for
# ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and
# executes commands from the FIRST one that exists and is readable. The
# --noprofile option may be used when the shell is started to inhibit this
# behaviour.

# linux loads bash_profile on login and bashrc for xterm (aka already logged in)
# Mac OS X terminal loads .bash_profile on starting Terminal :(

# So we set all login information in .bashrc
# We need to do two things here:

# 1. get *_to_path fns, ssource, umask and export  HIST*
. ~/.config/bash/env

# 2. Prevent it from being run later, since we need to use $BASH_ENV for
# non-login non-interactive shells.
# We don't export it, as we may have a non-login non-interactive shell as
# a child.
BASH_ENV=

# 3. Join the spanish inquisition. ;)
# so much for only two things...

# 4. alias to shell/login - set NAME EMAIL PAGER EDITOR
. ~/.config/bash/login

# 5.call shell/interactive and setup DIRENV, FZF for ! ESHELL
if [ "$PS1" ]; then
    . ~/.config/bash/interactive
fi

if [ -z "$ESHELL" ]; then
    # +-------------+
    # |  GITHUB     |
    # +-------------+

    # +-------------+
    # |   TROVE     |
    # +-------------+
    if dir_exists "${HOME}/work/tempo"; then
        export GITHUB_AUTH="$(gh auth token)"
        $HOME/work/tempo/trove-scripts/codeartifact/codeartifact_auth.py
        alias trove='poetry run trove'
    fi

fi

# +-------------+
# |    AWS      |
# +-------------+
alias assume="source assume"

# to avoid non-zero exit code
true
