# From bash manual:
# When an interactive shell that is not a login shell is started, Bash
# reads and executes commands from ~/.bashrc, if that file exists. This
# may be inhibited by using the --norc option. The --rcfile file option
# will force Bash to read and execute commands from file instead of
# ~/.bashrc.

# this file gets run in two cases:
# 1. non-login interactive shell
# 2. remote shell (over ssh or similar)

# #2 happens when you run "ssh user@host bash" explicitly.
# in this case, /etc/bash.bashrc has not been previous executed (unlike #1).
# however, we assume that #2 is a recovery mode, so we don't want to do much.
# (also, my google-fu didn't find a way to distinguish them)

# 1. get *_to_path fns, ssource, umask and export  HIST*
. ~/.config/bash/env
# 2.call shell/interactive and setup DIRENV, FZF for ! ESHELL
. ~/.config/bash/interactive
