# -*- mode: bash; -*-
# Emacs dumb terminal handling
if [[ "$TERM" == "dumb" && -n "$INSIDE_EMACS" ]]; then
  export INPUTRC=/dev/null
fi

# Base environment only
[[ -r "$HOME/.config/bash/env" ]] && . "$HOME/.config/bash/env"


# Interactive only
case $- in
  *i*)
      [[ -r "$HOME/.config/bash/interactive" ]] && . "$HOME/.config/bash/interactive"      
    ;;
esac
