name: run CI

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-y-test:
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v3
          
      - name: Run functional Melkor tests
        run: ./eru-new.sh test

      - name: Shape the world!
        run: ./eru-new.sh
